# Generated by Django 5.1.7 on 2025-03-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
